name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'release/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
        
      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      - name: Substring output
        run: echo ${{ steps.vars.outputs.short_ref:8 }}
