name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'release/**'
      
permissions: write-all

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set output
        id: vars
        run: echo ::set-output name=ref::${GITHUB_REF#refs/*/}
        
      - name: Check output
        run: echo ${{ steps.vars.outputs.ref }}
          
      - name: Update gradle version for Android
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: './pathway1/BasicsCodelab/app/build.gradle'
          version-name: '1.0.13'
          print-file: false
          
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ steps.vars.outputs.ref }}
          force: true
          message: '1.0.13 버전 변경'
