name: Update Version Name
on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set branch
        id: branch
        run: echo ::set-output name=ref::${GITHUB_REF#refs/*/}
        
      - name: Extract gradle version
        uses: bhowell2/github-substring-action@v1.0.0
        id: version
        with:
          value: ${{ steps.branch.outputs.ref }}
          index_of_str: "release/"

      - name: Update gradle version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: pathway1/BasicsCodelab/app/build.gradle
          versionName: ${{ steps.version.outputs.substring }}
          
      - name: Commit build.gradle
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ steps.branch.outputs.ref }}
          force: true
          message: ${{ steps.version.outputs.substring }} 버전 변경
